apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - global-config.yaml
  - secret.yaml
  - infra/mysql.yaml
  - infra/redis.yaml
  - infra/kafka.yaml
  - infra/elasticsearch.yaml
  - infra/prometheus.yaml
  - infra/grafana.yaml
  - infra/cert-issuer.yaml
  - infra/rarego-tls-certificate.yaml
  - apps/auth-service.yaml
  - apps/member-service.yaml
  - apps/auction-service.yaml
  - apps/product-service.yaml
  - apps/payment-service.yaml
  - apps/notification-service.yaml
  - ingress/ingress.yaml
  - ingress/monitoring-ingress.yaml
  - infra/internal-gateway.yaml

images:
  - name: rarego-auth-service
    newName: ghcr.io/prgrms-be-adv-devcourse/beadv4_4_bugzero_be-auth-service
  - name: rarego-member-service
    newName: ghcr.io/prgrms-be-adv-devcourse/beadv4_4_bugzero_be-member-service
  - name: rarego-auction-service
    newName: ghcr.io/prgrms-be-adv-devcourse/beadv4_4_bugzero_be-auction-service
  - name: rarego-product-service
    newName: ghcr.io/prgrms-be-adv-devcourse/beadv4_4_bugzero_be-product-service
  - name: rarego-payment-service
    newName: ghcr.io/prgrms-be-adv-devcourse/beadv4_4_bugzero_be-payment-service
  - name: rarego-notification-service
    newName: ghcr.io/prgrms-be-adv-devcourse/beadv4_4_bugzero_be-notification-service
  - name: rarego-product-elasticsearch
    newName: ghcr.io/prgrms-be-adv-devcourse/beadv4_4_bugzero_be-product-elasticsearch
    newTag: dev

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: prometheus-config
    files:
      - prometheus.yml=infra/monitoring/prometheus/prometheus.yml
  - name: grafana-datasources
    files:
      - datasources.yml=infra/monitoring/grafana/provisioning/datasources/datasources.yml
  - name: grafana-dashboard-provider
    files:
      - dashboards.yml=infra/monitoring/grafana/provisioning/dashboards/dashboards.yml
  - name: grafana-dashboards
    files:
      - business-kpi.json=infra/monitoring/grafana/dashboards/business-kpi.json
      - jvm-monitoring.json=infra/monitoring/grafana/dashboards/jvm-monitoring.json
      - service-overview.json=infra/monitoring/grafana/dashboards/service-overview.json
