apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: rarego
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: rarego-payment-service:latest
        ports:
        - containerPort: 8082
        resources:
          requests:
            memory: "256Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "300m"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8082
          initialDelaySeconds: 300
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8082
          initialDelaySeconds: 120
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 10
        startupProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8082
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 120
        env:
        - name: JAVA_OPTS
          value: "-Xms64m -Xmx128m -XX:+UseSerialGC -XX:MaxRAM=256m"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql:3306/rarego_payment?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul"
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        - name: TOSS_PAYMENTS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: toss-secret
              key: secret-key
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: secret
        - name: SPRING_DATA_REDIS_HOST
          value: "redis"
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: SPRING_PROFILES_ACTIVE
        - name: FRONT_URL
          valueFrom:
            secretKeyRef:
              name: global-secret
              key: FRONT_URL
        - name: INTERNAL_BACK_URL
          value: "http://rarego-nginx"
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: rarego
spec:
  selector:
    app: payment-service
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082
